# =============================================================================
# main.py  —  RAPA Engine FastAPI Service (Government-Ready API Layer)
# =============================================================================
#
# Endpoints:
#   GET /api/v1/quotes          Filtered, paginated flight quote feed
#   GET /api/v1/sector-heatmap  Aggregated fare averages per route
#   GET /api/v1/elasticity      Lead-time price elasticity analysis
#
# Run:
#   $env:PYTHONUTF8 = "1"
#   uvicorn main:app --reload --host 0.0.0.0 --port 8000
#
# Interactive API docs (auto-generated by FastAPI):
#   http://localhost:8000/docs       <- Swagger UI
#   http://localhost:8000/redoc      <- ReDoc UI
# =============================================================================

from __future__ import annotations

import os
import sqlite3
from contextlib import asynccontextmanager
from datetime import datetime, timezone
from typing import Literal, Optional

import pandas as pd
from fastapi import FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from pydantic import BaseModel, Field

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
DB_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "flight_quotes.db")

# Lead-time buckets (days before departure) for elasticity analysis
LEAD_TIME_BUCKETS = {
    "1_day":   (0,  2),
    "7_days":  (2,  10),
    "30_days": (10, 45),
    "60_days": (45, 999),
}


# =============================================================================
# Database helpers
# =============================================================================

def get_df() -> pd.DataFrame:
    """
    Load the entire flight_quotes table into a Pandas DataFrame.
    Raises HTTPException 503 if the database file is missing.
    """
    if not os.path.exists(DB_PATH):
        raise HTTPException(
            status_code=503,
            detail=(
                f"Database not found at {DB_PATH}. "
                "Run 'python db_setup.py' and 'python processor.py' first."
            ),
        )
    conn = sqlite3.connect(DB_PATH)
    df = pd.read_sql_query("SELECT * FROM flight_quotes", conn)
    conn.close()

    # Parse departure timestamp — keep a numeric days-to-departure column
    df["departure_dt"] = pd.to_datetime(df["departure_timestamp"], errors="coerce")
    today = datetime.now(timezone.utc).replace(tzinfo=None)
    df["days_to_departure"] = (df["departure_dt"] - today).dt.days

    return df


# =============================================================================
# Response Schemas  (Pydantic models for API output documentation)
# =============================================================================

class QuoteRecord(BaseModel):
    id: int
    flight_number: str
    airline: str
    origin_sector: str
    destination_sector: str
    departure_timestamp: str
    base_fare: float
    taxes: float
    user_development_fee: float
    convenience_charge: float
    total_fare: float
    seat_status: str
    is_math_valid: bool
    is_price_outlier: bool
    source_file: Optional[str] = None
    ingestion_timestamp: Optional[str] = None


class QuotesResponse(BaseModel):
    total: int
    page: int
    page_size: int
    results: list[QuoteRecord]


class RouteHeatmapEntry(BaseModel):
    route: str
    origin_sector: str
    destination_sector: str
    avg_total_fare: float
    min_fare: float
    max_fare: float
    flight_count: int
    airlines: list[str]


class HeatmapResponse(BaseModel):
    generated_at: str
    routes: list[RouteHeatmapEntry]


class ElasticityBucket(BaseModel):
    bucket: str
    label: str
    days_range: str
    avg_fare: float
    min_fare: float
    max_fare: float
    flight_count: int
    fare_change_pct: Optional[float] = Field(
        None, description="Percentage fare change vs. previous bucket (null for first bucket)"
    )


class ElasticityResponse(BaseModel):
    generated_at: str
    description: str
    buckets: list[ElasticityBucket]


class HealthResponse(BaseModel):
    status: str
    database: str
    record_count: int
    timestamp: str


# =============================================================================
# App lifecycle
# =============================================================================

@asynccontextmanager
async def lifespan(app: FastAPI):
    """Startup: verify DB exists. Shutdown: nothing to clean up."""
    if not os.path.exists(DB_PATH):
        print(f"WARNING: Database not found at {DB_PATH}. Run the pipeline first.")
    else:
        conn = sqlite3.connect(DB_PATH)
        count = conn.execute("SELECT COUNT(*) FROM flight_quotes").fetchone()[0]
        conn.close()
        print(f"RAPA Engine API started. Database: {DB_PATH} ({count} records)")
    yield


# =============================================================================
# FastAPI Application
# =============================================================================

app = FastAPI(
    title="RAPA Engine — Flight Quotes API",
    description=(
        "Government-ready REST API for flight quote analytics. "
        "Powered by Gemini 3.6 Flash structured extraction."
    ),
    version="1.0.0",
    lifespan=lifespan,
    contact={
        "name": "savanthkumarvedesh-code",
        "url": "https://github.com/savanthkumarvedesh-code/rapa-engine",
    },
)

# Allow cross-origin requests (for Streamlit dashboard on different port)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["GET"],
    allow_headers=["*"],
)


# =============================================================================
# ENDPOINT 1: Health check
# =============================================================================

@app.get("/health", response_model=HealthResponse, tags=["System"])
def health_check():
    """
    Health check endpoint. Returns database status and record count.
    Useful for monitoring and orchestration tools.
    """
    if not os.path.exists(DB_PATH):
        return HealthResponse(
            status="degraded",
            database="not_found",
            record_count=0,
            timestamp=datetime.utcnow().isoformat(),
        )
    conn = sqlite3.connect(DB_PATH)
    count = conn.execute("SELECT COUNT(*) FROM flight_quotes").fetchone()[0]
    conn.close()
    return HealthResponse(
        status="healthy",
        database=DB_PATH,
        record_count=count,
        timestamp=datetime.utcnow().isoformat(),
    )


# =============================================================================
# ENDPOINT 2: GET /api/v1/quotes
# =============================================================================

@app.get(
    "/api/v1/quotes",
    response_model=QuotesResponse,
    tags=["Quotes"],
    summary="Filtered Flight Quote Feed",
    description=(
        "Returns a paginated, filtered list of flight quotes from the database. "
        "Supports filtering by airline, route, seat status, fare range, and outlier flag."
    ),
)
def get_quotes(
    airline: Optional[str] = Query(None, description="Filter by airline name (partial match)"),
    origin: Optional[str] = Query(None, description="Filter by 3-letter origin IATA code, e.g. DEL"),
    destination: Optional[str] = Query(None, description="Filter by 3-letter destination IATA code, e.g. BOM"),
    seat_status: Optional[Literal["available", "sold-out", "cancelled"]] = Query(
        None, description="Filter by seat availability status"
    ),
    min_fare: Optional[float] = Query(None, description="Minimum total fare (INR)"),
    max_fare: Optional[float] = Query(None, description="Maximum total fare (INR)"),
    outliers_only: bool = Query(False, description="If true, return only price outlier records"),
    math_invalid_only: bool = Query(False, description="If true, return only records with invalid fare math"),
    page: int = Query(1, ge=1, description="Page number (1-indexed)"),
    page_size: int = Query(20, ge=1, le=100, description="Results per page (max 100)"),
):
    df = get_df()

    # Apply filters progressively
    if airline:
        df = df[df["airline"].str.contains(airline, case=False, na=False)]
    if origin:
        df = df[df["origin_sector"].str.upper() == origin.upper()]
    if destination:
        df = df[df["destination_sector"].str.upper() == destination.upper()]
    if seat_status:
        df = df[df["seat_status"] == seat_status]
    if min_fare is not None:
        df = df[df["total_fare"] >= min_fare]
    if max_fare is not None:
        df = df[df["total_fare"] <= max_fare]
    if outliers_only:
        df = df[df["is_price_outlier"] == 1]
    if math_invalid_only:
        df = df[df["is_math_valid"] == 0]

    total = len(df)
    # Pagination
    start = (page - 1) * page_size
    end = start + page_size
    page_df = df.iloc[start:end]

    results = []
    for _, row in page_df.iterrows():
        results.append(
            QuoteRecord(
                id=int(row.get("id", 0)),
                flight_number=str(row["flight_number"]),
                airline=str(row["airline"]),
                origin_sector=str(row["origin_sector"]),
                destination_sector=str(row["destination_sector"]),
                departure_timestamp=str(row["departure_timestamp"]),
                base_fare=float(row["base_fare"]),
                taxes=float(row["taxes"]),
                user_development_fee=float(row["user_development_fee"]),
                convenience_charge=float(row["convenience_charge"]),
                total_fare=float(row["total_fare"]),
                seat_status=str(row["seat_status"]),
                is_math_valid=bool(row["is_math_valid"]),
                is_price_outlier=bool(row["is_price_outlier"]),
                source_file=str(row.get("source_file", "") or ""),
                ingestion_timestamp=str(row.get("ingestion_timestamp", "") or ""),
            )
        )

    return QuotesResponse(total=total, page=page, page_size=page_size, results=results)


# =============================================================================
# ENDPOINT 3: GET /api/v1/sector-heatmap
# =============================================================================

@app.get(
    "/api/v1/sector-heatmap",
    response_model=HeatmapResponse,
    tags=["Analytics"],
    summary="Sector-wise Fare Heatmap",
    description=(
        "Returns aggregated average, min, and max fare for each origin→destination "
        "route. Use this data to render a pricing heatmap by sector."
    ),
)
def get_sector_heatmap(
    seat_status: Optional[Literal["available", "sold-out", "cancelled"]] = Query(
        None, description="Filter by seat status before aggregating"
    ),
    exclude_outliers: bool = Query(
        True, description="Exclude price outlier records from averages (recommended)"
    ),
):
    df = get_df()

    if seat_status:
        df = df[df["seat_status"] == seat_status]
    if exclude_outliers:
        df = df[df["is_price_outlier"] == 0]

    if df.empty:
        raise HTTPException(status_code=404, detail="No data found for the given filters.")

    # Aggregate per route
    df["route"] = df["origin_sector"] + "->" + df["destination_sector"]
    grouped = df.groupby(["route", "origin_sector", "destination_sector"]).agg(
        avg_total_fare=("total_fare", "mean"),
        min_fare=("total_fare", "min"),
        max_fare=("total_fare", "max"),
        flight_count=("total_fare", "count"),
        airlines=("airline", lambda x: sorted(x.unique().tolist())),
    ).reset_index()

    routes = []
    for _, row in grouped.iterrows():
        routes.append(
            RouteHeatmapEntry(
                route=str(row["route"]),
                origin_sector=str(row["origin_sector"]),
                destination_sector=str(row["destination_sector"]),
                avg_total_fare=round(float(row["avg_total_fare"]), 2),
                min_fare=round(float(row["min_fare"]), 2),
                max_fare=round(float(row["max_fare"]), 2),
                flight_count=int(row["flight_count"]),
                airlines=row["airlines"],
            )
        )

    return HeatmapResponse(
        generated_at=datetime.utcnow().isoformat(),
        routes=sorted(routes, key=lambda r: r.avg_total_fare, reverse=True),
    )


# =============================================================================
# ENDPOINT 4: GET /api/v1/elasticity
# =============================================================================

@app.get(
    "/api/v1/elasticity",
    response_model=ElasticityResponse,
    tags=["Analytics"],
    summary="Lead-Time Price Elasticity",
    description=(
        "Calculates average fares grouped by how many days remain before departure. "
        "Reveals how prices change as departure approaches (elasticity). "
        "Buckets: 0-2 days (last-minute), 2-10 days (short), 10-45 days (medium), 45+ days (advance)."
    ),
)
def get_elasticity(
    route: Optional[str] = Query(
        None, description="Filter to a specific route, e.g. 'DEL->BOM'"
    ),
    airline: Optional[str] = Query(None, description="Filter by airline name"),
):
    df = get_df()

    if route:
        # Accept both 'DEL->BOM' and 'DEL-BOM' formats
        route_norm = route.replace("->", "-").replace(" ", "")
        df["route"] = df["origin_sector"] + "-" + df["destination_sector"]
        df = df[df["route"].str.upper() == route_norm.upper()]

    if airline:
        df = df[df["airline"].str.contains(airline, case=False, na=False)]

    if df.empty:
        raise HTTPException(status_code=404, detail="No data found for the given filters.")

    # Drop rows without valid departure dates
    df = df.dropna(subset=["days_to_departure"])

    BUCKET_LABELS = {
        "1_day":   "Last Minute (0-2 days)",
        "7_days":  "Short Lead (2-10 days)",
        "30_days": "Medium Lead (10-45 days)",
        "60_days": "Advance Booking (45+ days)",
    }

    buckets_out: list[ElasticityBucket] = []
    prev_avg: Optional[float] = None

    for bucket_key, (low, high) in LEAD_TIME_BUCKETS.items():
        mask = (df["days_to_departure"] >= low) & (df["days_to_departure"] < high)
        bucket_df = df[mask]

        if bucket_df.empty:
            # Include bucket with zero count so the chart is complete
            buckets_out.append(
                ElasticityBucket(
                    bucket=bucket_key,
                    label=BUCKET_LABELS[bucket_key],
                    days_range=f"{low}-{high if high < 999 else '+'} days",
                    avg_fare=0.0,
                    min_fare=0.0,
                    max_fare=0.0,
                    flight_count=0,
                    fare_change_pct=None,
                )
            )
            continue

        avg = float(bucket_df["total_fare"].mean())
        change_pct = None
        if prev_avg is not None and prev_avg > 0:
            change_pct = round((avg - prev_avg) / prev_avg * 100, 2)

        buckets_out.append(
            ElasticityBucket(
                bucket=bucket_key,
                label=BUCKET_LABELS[bucket_key],
                days_range=f"{low}-{high if high < 999 else '+'} days",
                avg_fare=round(avg, 2),
                min_fare=round(float(bucket_df["total_fare"].min()), 2),
                max_fare=round(float(bucket_df["total_fare"].max()), 2),
                flight_count=int(len(bucket_df)),
                fare_change_pct=change_pct,
            )
        )
        prev_avg = avg

    return ElasticityResponse(
        generated_at=datetime.utcnow().isoformat(),
        description=(
            "Price elasticity by lead time. "
            "fare_change_pct > 0 means fares rise as departure approaches (typical). "
            "fare_change_pct < 0 means fares drop (last-minute discounts)."
        ),
        buckets=buckets_out,
    )
